
# Phase 1: add Pydantic models for PaymentRequest, AgentStep, DecisionResponse
# from pydantic import BaseModel, Field
# class PaymentRequest(BaseModel): ...
# class AgentStep(BaseModel): ...
# class DecisionResponse(BaseModel): ...
